### ISSUE TITLE
authorization mechanism invalid /AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by Smithfields** [grails-aws/grails-aws#57]
Hello, it's the first time I'm using the plugin and I'm having the following error: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>

my config : 
        aws {
            credentials {
                accessKey = "xxxxxxx"
                secretKey = "xxxxxxxxxxxxxxxxxxxxx"
            }
            s3 {
                bucket = "deysmnwarehouse"
                bucketLocation = "Frankfurt"//eu-central-1
                acl = "public"

                rrs = true
            }
        }

call (in boostrap)>>>         
new File(fileStr).s3upload {
            path "userupload"
        }

here' the stack trace >>>

context.GrailsContextLoaderListener Error initializing the application: S3 Error Message.
org.jets3t.service.S3ServiceException: S3 Error Message. -- ResponseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>1FE3EC356D323A26</RequestId><HostId>xxxxxxxxxxxxxxxxxxxxx=</HostId></Error>
	at org.jets3t.service.S3Service.putObject(S3Service.java:2267)
	at grails.plugin.aws.s3.S3FileUpload.fileUpload(S3FileUpload.groovy:110)
	at grails.plugin.aws.util.MetaClassInjector$_injectS3UploadMethods_closure2.doCall(MetaClassInjector.groovy:42)
	at BootStrap$_closure1.doCall(BootStrap.groovy:275)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by j4y** [comment]
This is because Frankfurt is the wrong bucketLocation.

You want to use:
http://jets3t.s3.amazonaws.com/api/org/jets3t/service/model/S3Bucket.html#LOCATION_EU_FRANKFURT

```
public static final java.lang.String 	LOCATION_EU_FRANKFURT 	"eu-central-1"
```

So if you just replace "Frankfurt" with "eu-central-1" it should work.

**Comment by Smithfields** [comment]
... I knew it. Accept my apologies for this useless issue report. Many Thanks for your answer and for your plugin.

**Comment by j4y** [comment]
Maybe we should update the documentation to be more clear?

The `bucketLocation` parameter could be named as `region`.

**Comment by ssxenon01** [comment]
My application was working fine. Suddenly it gives that error too. I haven't changed anything. Any update on this ?

**Comment by ssxenon01** [comment]
Tried every possible combinations still not working. Event changed access keys still same

**Comment by j4y** [comment]
Can you provide a stacktrace and your configuration?

**Comment by Smithfields** [comment]
Still having the issue, stacktrace is not really helping since, I guess, much of the error is handled at a lower level. 

I'm using 
Java 1.8.0_u65
Grails 2.5.2
tomcat:8.0.22
cache:1.1.8'
cache-ehcache:1.0.5
aws:1.9.13.4

**Comment by j4y** [comment]
I disagree.  A stacktrace will provide information that will show the line of code with the problem.  Please provide one or this issue will be closed.

v1.9.13.4 works fine for me, but i'm in us-east

**Comment by ssxenon01** [comment]
As mentioned here http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html

In the China (Beijing) and EU (Frankfurt) regions, Amazon S3 supports only Signature Version 4, and AWS SDKs use this signature version to authenticate requests.

it seems setting global property doesn't affecting:

System.setProperty(SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY, "true");

How can we enable v4?

**Comment by Smithfields** [comment]
I tried 
> new File('myFile.txt').s3upload {}

> }catch(Throwable t)  ...
> }catch(Exception ex) ...
> org.apache.log4j.LogManager.getLogger("StackTrace")

none of them reported decent Stacktrace, they were all mentioning same error as written in the initial message. Does aws plugin can be configured in some sort of 'verbose' / debug mode?

**Comment by ssxenon01** [comment]
@Smithfields try to catch with S3ServiceException
```
catch (S3ServiceException e){
                print e.s3ErrorCode
                print e.s3ErrorMessage
                print "what ---------"
            }
```

**Comment by ssxenon01** [comment]
as i mentioned before: aws sdk uses Signature Version 2 by default. And plugin won't change it by following property as it should
```System.setProperty(SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY, "true");```
>In the China (Beijing) and EU (Frankfurt) regions, Amazon S3 supports only Signature Version 4, and >AWS SDKs use this signature version to authenticate requests.

>In all other regions, Amazon S3 supports both Signature Version 4 and Signature Version 2. For these >regions, AWS SDKs use Signature Version 2 by default to authenticate requests. You can optionally >request the SDKs to use

**Comment by ssxenon01** [comment]
Just found out that jets3t not supperted v4 requests. V4 support added since v.0.9.3.
so quick fix could be adding following to your dependencies:
```compile 'net.java.dev.jets3t:jets3t:0.9.4'```
and excluding jets3t from your plugin:
```runtime(':aws:1.9.13.4'){
    exclude 'jets3t'
}```

**Comment by ssxenon01** [comment]
at last here is [input stream issue](https://bitbucket.org/jmurty/jets3t/issues/206/093-signature-v4-put-with-inputstream-does) on file upload. Until it implemented properly, We can't use inputstream upload on frankfurt and china servers.
